// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjayoootraeyzgyhbhrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlqYXlvb290cmFleXpneWhiaHJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzMjkxMTksImV4cCI6MjA2ODkwNTExOX0.KGNOjF4kMixPwon4WiYY4Q7E1Pu7R3onzHaNBCMy2rY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});